name: DAILY MAKER

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
    
concurrency:
  group: xtream-system
  cancel-in-progress: false
      
jobs:
   part1:
    name: Proxy Sistemi
    runs-on: ubuntu-latest
    env:
      M3U_REPO_TOKEN: ${{ secrets.M3U_REPO_TOKEN }}

    steps:
      - name: Checkout public repo (main)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.M3U_REPO_TOKEN }}@github.com/opitiopiti/tumsistem.git private_py

      - name: Run proxy_guncelleme Script
        run: python private_py/sinewix/proxyarama.py || true 
        
      - name: Commit and Push Ana JSONs to public repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sinewix/pro.txt || echo "No pro sinewix"
          git commit -m "Sinewix Pro Guncellendi[auto]" || echo "No changes"
          git push origin main
          
  part2:
    name: sinewix
    runs-on: ubuntu-latest
    need: part1
    env:
      M3U_REPO_TOKEN: ${{ secrets.M3U_REPO_TOKEN }}
      
    steps:
      - name: Checkout public repo (main)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: git clone https://x-access-token:${{ secrets.M3U_REPO_TOKEN }}@github.com/opitiopiti/tumsistem.git private_py

      - name: Install Shared Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml aiohttp aiofiles dotenv httpx
          
      - name: Run sinewixanime.py Script
        run: python private_py/sinewix/sinewixanimeler.py || true

      - name: Run sinewixfilmler.py Script
        run: python private_py/sinewix/sinewixfilmler.py || true
        
      - name: Run sinewixseries.py Script
        run: python private_py/sinewix/sinewixseries.py || true
        
      - name: Sync M3U outputs to private repo
        run: |
          git clone https://x-access-token:${{ secrets.M3U_REPO_TOKEN }}@github.com/opitiopiti/sinewix.git privaate_sinewix

          cp sinewix_filmler.m3u privaate_sinewix/sinewix_filmler.m3u || echo "sinewix_filmler bulunamadı"
          cp sinewix_animeler.m3u privaate_sinewix/sinewix_animeler.m3u || echo "sinewix_animeler bulunamadı"
          cp sinewix_diziler.m3u privaate_sinewix/sinewix_diziler.m3u || echo "sinewix_diziler bulunamadı"
          
          cd privaate_sinewix
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto sinewix playlist update" || echo "No changes"
          git push origin main
          
  part3:
    name: dizibol
    runs-on: ubuntu-latest
    need: part2
    env:
      M3U_REPO_TOKEN: ${{ secrets.M3U_REPO_TOKEN }}
      
    steps:
      - name: Checkout public repo (main)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Py Repo
        run: git clone https://x-access-token:${{ secrets.M3U_REPO_TOKEN }}@github.com/opitiopiti/tumsistem.git private_py

      - name: Install Shared Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml aiohttp aiofiles dotenv httpx
          
      - name: Run dizibol.py Script
        run: python private_py/dizibol/tumdiziler.py || true
       
      - name: Sync M3U outputs to private repo
        run: |
          git clone https://x-access-token:${{ secrets.M3U_REPO_TOKEN }}@github.com/opitiopiti/sinewix.git privaate_dizibol

          cp dizibol.m3u privaate_dizibol/dizibol.m3u || echo "dizibol bulunamadı"
          
          cd privaate_dizibol
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto dizibol playlist update" || echo "No changes"
          git push origin main          
