name: Cache Temizlik Telegram

on:
  workflow_dispatch:

jobs:
  cachetemizlik-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Clean Cache Xtream
        id: cache_step
        env:
          CLEAN_CACHE_URL: ${{ secrets.CLEAN_CACHE }}
        run: |
          echo "Cache temizleme isteği atılıyor..."

          STATUS=$(curl -sS -L \
            --max-redirs 5 \
            --retry 3 \
            --retry-delay 2 \
            --fail-with-body \
            -o /dev/null \
            -w "%{http_code}" \
            "$CLEAN_CACHE_URL") || STATUS="000"

          echo "HTTP STATUS: $STATUS"

          if [[ "$STATUS" == "200" ]]; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Telegram Success Notification
        if: steps.cache_step.outputs.success == 'true'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -o /dev/null -X POST \
            "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d text="🚀✨ XTREAM SISTEMI BASARIYLA GUNCELLENDI ✅🔥"

      - name: Telegram Fail Notification
        if: steps.cache_step.outputs.success == 'false'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -o /dev/null -X POST \
            "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d text="❌⚠️ XTREAM SISTEMI GUNCELLENEMEDI!"
